import { loadFlowFmAvailabilityOwnerView } from '/shared/flow-fm-availability-admin.js?v=0.10.81.3';
import { FLOW_FM_INNER_SEASONS,FLOW_FM_WEEKDAYS,formatFlowFmAvailabilityTime } from '/shared/flow-fm-availability-core.js?v=0.10.81.3';
import { timezoneDisplayName,timezoneShortName } from '/shared/timezone-labels.js?v=0.10.81.3';
const summary=document.getElementById('availabilitySummary'),toolbar=document.getElementById('availabilityToolbar'),search=document.getElementById('availabilitySearch'),filter=document.getElementById('availabilityFilter'),message=document.getElementById('availabilityMessage'),grid=document.getElementById('availabilityMemberGrid'),gate=document.getElementById('availabilityGate');let rows=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const title=v=>String(v||'').replace(/^Inner\s+/,'');
function localParts(tz,d=new Date()){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:tz||'America/Los_Angeles',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d),m=Object.fromEntries(p.map(x=>[x.type,x.value])),w={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};return{weekday:w[m.weekday]||0,time:`${m.hour==='24'?'00':m.hour}:${m.minute}`}}catch{return{weekday:0,time:''}}}
const dayStateFor=(r,s,w)=>(r.day_states||[]).find(x=>x.inner_season===s&&Number(x.weekday)===Number(w))||null;
function isAvailableNow(r){const season=String(r.current_inner_season||'');if(!season)return false;const {weekday,time}=localParts(r.timezone),state=dayStateFor(r,season,weekday);if(state&&state.is_available!==true)return false;return(r.windows||[]).some(x=>x.inner_season===season&&Number(x.weekday)===weekday&&String(x.starts_at)<=time&&String(x.ends_at)>time)}
const recent=v=>{const n=new Date(v||0).getTime();return Number.isFinite(n)&&n>Date.now()-7*86400000};
const updated=v=>{if(!v)return'No rhythm saved yet';const d=new Date(v);return Number.isNaN(d.getTime())?'Update date unavailable':`Updated ${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)}`};
const statusFor=(r,s)=>(r.season_status||[]).find(x=>x.inner_season===s)||null;
function exactDays(r,s){return FLOW_FM_WEEKDAYS.map(day=>{const state=dayStateFor(r,s,day.weekday),windows=(r.windows||[]).filter(x=>x.inner_season===s&&Number(x.weekday)===day.weekday);return{...day,available:state?state.is_available===true:windows.length>0,windows}})}
function seasonMarkup(r,s){const st=statusFor(r,s),days=exactDays(r,s),open=days.filter(d=>d.available&&d.windows.length);if(!open.length){const resting=st&&st.accepting_calls===false;return`<article class="availability-season ${resting?'':'is-incomplete'}"><header><small>${esc(title(s))}</small><span class="availability-season-status">${resting?'Saved':'Incomplete'}</span></header><p class="availability-resting">${resting?'Resting from calls this season.':'No days and times have been saved yet.'}</p></article>`}return`<article class="availability-season"><header><small>${esc(title(s))}</small><span class="availability-season-status">${open.length} ${open.length===1?'day':'days'}</span></header><div class="availability-day-list">${open.map(d=>`<div class="availability-day"><strong>${esc(d.label)}</strong><span>${d.windows.map(w=>`${formatFlowFmAvailabilityTime(w.starts_at)}–${formatFlowFmAvailabilityTime(w.ends_at)}`).join('<br>')}</span></div>`).join('')}</div></article>`}
function card(r){const photo=r.profile_photo_url||'/assets/flowtel-pinkrose.png',zone=timezoneDisplayName(r.timezone,new Date()),short=timezoneShortName(r.timezone,new Date()),open=isAvailableNow(r),complete=Number(r.completed_season_count||0);return`<article class="availability-member-card"><header><img src="${esc(photo)}" alt="" onerror="this.onerror=null;this.src='/assets/flowtel-pinkrose.png'"><div><p class="eyebrow">${String(r.membership_type||'').toLowerCase()==='council'?'COUNCIL':'FLOW FM'}</p><h2>${esc(r.display_name||'Flow FM Member')}</h2><p>${esc(r.location||'Location not entered')}</p></div><span class="availability-now ${open?'is-open':''}">${open?'Available Now':'Not currently available'}</span></header><div class="availability-member-meta"><span>${esc(zone||r.timezone||'Timezone not entered')}${short&&!String(zone||'').includes(`(${short})`)?` (${esc(short)})`:''}</span><span>${complete}/4 seasons saved</span><span>${r.mentor_accepting_clients?'Accepting Clients':'Not Accepting Clients'}</span><span>${r.concierge_access_enabled?'Concierge Team':'No Concierge Access'}</span><span>${esc(updated(r.availability_updated_at))}</span></div><div class="availability-season-grid">${FLOW_FM_INNER_SEASONS.map(s=>seasonMarkup(r,s)).join('')}</div></article>`}
function filtered(){const q=String(search.value||'').trim().toLowerCase(),mode=filter.value;return rows.filter(r=>(!q||`${r.display_name||''} ${r.location||''} ${r.email||''}`.toLowerCase().includes(q))&&(mode!=='available_now'||isAvailableNow(r))&&(mode!=='accepting_clients'||r.mentor_accepting_clients===true)&&(mode!=='incomplete'||Number(r.completed_season_count||0)<4)&&(mode!=='recently_updated'||recent(r.availability_updated_at)))}
function render(){const v=filtered();grid.innerHTML=v.length?v.map(card).join(''):'<p class="availability-empty">No Priestesses match this view.</p>'}
function renderSummary(){const started=rows.filter(r=>Number(r.completed_season_count||0)>0).length,open=rows.filter(isAvailableNow).length,recentCount=rows.filter(r=>recent(r.availability_updated_at)).length;summary.hidden=false;summary.innerHTML=`<article><small>FLOW FM + COUNCIL</small><strong>${rows.length}</strong><span>members</span></article><article><small>RHYTHMS STARTED</small><strong>${started}</strong><span>members</span></article><article><small>AVAILABLE NOW</small><strong>${open}</strong><span>in their saved rhythm</span></article><article><small>UPDATED THIS WEEK</small><strong>${recentCount}</strong><span>members</span></article>`}
async function init(){try{rows=await loadFlowFmAvailabilityOwnerView();message.textContent='';toolbar.hidden=false;renderSummary();render()}catch(e){message.textContent='';gate.hidden=false;gate.innerHTML=`<p class="eyebrow">OWNER ADMINISTRATION</p><h2>Availability could not be opened.</h2><p>${esc(e?.message||'Run migration 065, then return to this room.')}</p>`}}search.addEventListener('input',render);filter.addEventListener('change',render);init();
