import { loadFlowFmAvailabilityOwnerView, loadFlowFmAvailabilityMonthOwnerView, acknowledgeFlowFmAvailabilityMonth } from '/shared/flow-fm-availability-admin.js?v=0.10.83';
import { FLOW_FM_INNER_SEASONS,FLOW_FM_WEEKDAYS,formatFlowFmAvailabilityTime } from '/shared/flow-fm-availability-core.js?v=0.10.83';
import { timezoneDisplayName,timezoneShortName } from '/shared/timezone-labels.js?v=0.10.83';

const summary=document.getElementById('availabilitySummary');
const toolbar=document.getElementById('availabilityToolbar');
const search=document.getElementById('availabilitySearch');
const filter=document.getElementById('availabilityFilter');
const message=document.getElementById('availabilityMessage');
const grid=document.getElementById('availabilityMemberGrid');
const gate=document.getElementById('availabilityGate');
const updateQueue=document.getElementById('availabilityUpdateQueue');
const updateCount=document.getElementById('availabilityUpdateCount');
const updateList=document.getElementById('availabilityUpdateList');
let rows=[];
let monthUpdates=[];

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const title=v=>String(v||'').replace(/^Inner\s+/,'');
function isoDateObject(value){return /^\d{4}-\d{2}-\d{2}$/.test(String(value||''))?new Date(`${value}T12:00:00Z`):null;}
function monthLabel(value){const d=isoDateObject(value);return d?new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(d):String(value||'Month');}
function localParts(tz,d=new Date()){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:tz||'America/Los_Angeles',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d),m=Object.fromEntries(p.map(x=>[x.type,x.value])),w={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};return{weekday:w[m.weekday]||0,time:`${m.hour==='24'?'00':m.hour}:${m.minute}`}}catch{return{weekday:0,time:''}}}
const dayStateFor=(r,s,w)=>(r.day_states||[]).find(x=>x.inner_season===s&&Number(x.weekday)===Number(w))||null;
function isAvailableNow(r){const season=String(r.current_inner_season||'');if(!season)return false;const {weekday,time}=localParts(r.timezone),state=dayStateFor(r,season,weekday);if(state&&state.is_available!==true)return false;return(r.windows||[]).some(x=>x.inner_season===season&&Number(x.weekday)===weekday&&String(x.starts_at)<=time&&String(x.ends_at)>time)}
const recent=v=>{const n=new Date(v||0).getTime();return Number.isFinite(n)&&n>Date.now()-7*86400000};
const updated=v=>{if(!v)return'No rhythm saved yet';const d=new Date(v);return Number.isNaN(d.getTime())?'Update date unavailable':`Updated ${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)}`};
const statusFor=(r,s)=>(r.season_status||[]).find(x=>x.inner_season===s)||null;
function exactDays(r,s){return FLOW_FM_WEEKDAYS.map(day=>{const state=dayStateFor(r,s,day.weekday),windows=(r.windows||[]).filter(x=>x.inner_season===s&&Number(x.weekday)===day.weekday);return{...day,available:state?state.is_available===true:windows.length>0,windows}})}
function seasonMarkup(r,s){const st=statusFor(r,s),days=exactDays(r,s),open=days.filter(d=>d.available&&d.windows.length);if(!open.length){const resting=st&&st.accepting_calls===false;return`<article class="availability-season ${resting?'':'is-incomplete'}"><header><small>${esc(title(s))}</small><span class="availability-season-status">${resting?'Saved':'Incomplete'}</span></header><p class="availability-resting">${resting?'Resting from calls this season.':'No days and times have been saved yet.'}</p></article>`}return`<article class="availability-season"><header><small>${esc(title(s))}</small><span class="availability-season-status">${open.length} ${open.length===1?'day':'days'}</span></header><div class="availability-day-list">${open.map(d=>`<div class="availability-day"><strong>${esc(d.label)}</strong><span>${d.windows.map(w=>`${formatFlowFmAvailabilityTime(w.starts_at)}–${formatFlowFmAvailabilityTime(w.ends_at)}`).join('<br>')}</span></div>`).join('')}</div></article>`}
function pendingMonthsFor(memberId){return monthUpdates.filter(item=>item.member_id===memberId&&item.pending_owner_update===true)}
function card(r){const photo=r.profile_photo_url||'/assets/flowtel-pinkrose.png',zone=timezoneDisplayName(r.timezone,new Date()),short=timezoneShortName(r.timezone,new Date()),open=isAvailableNow(r),complete=Number(r.completed_season_count||0),pending=pendingMonthsFor(r.member_id).length;return`<article class="availability-member-card"><header><img src="${esc(photo)}" alt="" onerror="this.onerror=null;this.src='/assets/flowtel-pinkrose.png'"><div><p class="eyebrow">${String(r.membership_type||'').toLowerCase()==='council'?'COUNCIL':'FLOW FM'}</p><h2>${esc(r.display_name||'Flow FM Member')}</h2><p>${esc(r.location||'Location not entered')}</p></div><span class="availability-now ${open?'is-open':''}">${open?'Available Now':'Not currently available'}</span></header><div class="availability-member-meta"><span>${esc(zone||r.timezone||'Timezone not entered')}${short&&!String(zone||'').includes(`(${short})`)?` (${esc(short)})`:''}</span><span>${complete}/4 seasons saved</span><span>${r.mentor_accepting_clients?'Accepting Clients':'Not Accepting Clients'}</span><span>${r.concierge_access_enabled?'Concierge Team':'No Concierge Access'}</span><span>${esc(updated(r.availability_updated_at))}</span>${pending?`<span class="availability-pending-chip">${pending} Acuity ${pending===1?'update':'updates'} waiting</span>`:''}</div><div class="availability-season-grid">${FLOW_FM_INNER_SEASONS.map(s=>seasonMarkup(r,s)).join('')}</div></article>`}
function filtered(){const q=String(search.value||'').trim().toLowerCase(),mode=filter.value;return rows.filter(r=>(!q||`${r.display_name||''} ${r.location||''} ${r.email||''}`.toLowerCase().includes(q))&&(mode!=='available_now'||isAvailableNow(r))&&(mode!=='accepting_clients'||r.mentor_accepting_clients===true)&&(mode!=='incomplete'||Number(r.completed_season_count||0)<4)&&(mode!=='recently_updated'||recent(r.availability_updated_at))&&(mode!=='needs_acuity'||pendingMonthsFor(r.member_id).length>0))}
function render(){const v=filtered();grid.innerHTML=v.length?v.map(card).join(''):'<p class="availability-empty">No Priestesses match this view.</p>'}
function renderSummary(){const started=rows.filter(r=>Number(r.completed_season_count||0)>0).length,open=rows.filter(isAvailableNow).length,pending=monthUpdates.filter(r=>r.pending_owner_update===true).length;summary.hidden=false;summary.innerHTML=`<article><small>FLOW FM + COUNCIL</small><strong>${rows.length}</strong><span>members</span></article><article><small>RHYTHMS STARTED</small><strong>${started}</strong><span>members</span></article><article><small>AVAILABLE NOW</small><strong>${open}</strong><span>in their saved rhythm</span></article><article class="${pending?'has-attention':''}"><small>ACUITY UPDATES</small><strong>${pending}</strong><span>${pending?'waiting for you':'all caught up'}</span></article>`}
function updateWindowLabel(window){return `${formatFlowFmAvailabilityTime(window.start)}–${formatFlowFmAvailabilityTime(window.end)}`}
function ownerMonthCalendar(item){const days=Array.isArray(item.days)?item.days:[],first=isoDateObject(item.month_start),leading=first?(first.getUTCDay()+6)%7:0,total=leading+days.length,trailing=(7-(total%7))%7;const blanks=Array.from({length:leading},()=>'<div class="owner-month-blank"></div>').join(''),end=Array.from({length:trailing},()=>'<div class="owner-month-blank"></div>').join('');const cells=days.map(day=>{const d=isoDateObject(day.calendar_date),n=d?d.getUTCDate():'—',windows=Array.isArray(day.windows)?day.windows:[],available=day.is_available===true&&windows.length,season=String(day.projected_inner_season||'').replace('Inner ','');return`<div class="owner-month-day ${available?'has-availability':''} ${day.is_override?'is-override':''}"><strong>${esc(n)}</strong><div>${available?windows.map(w=>`<span>${esc(updateWindowLabel(w))}</span>`).join(''):''}</div><small>${esc(season)}</small></div>`}).join('');return`<div class="owner-month-scroll"><div class="owner-month-weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="owner-month-grid">${blanks}${cells}${end}</div></div>`}
function updateReason(item){const updatedAt=new Date(item.updated_at||0).getTime(),submittedAt=new Date(item.last_submitted_at||item.first_submitted_at||0).getTime();return Number.isFinite(updatedAt)&&Number.isFinite(submittedAt)&&updatedAt>submittedAt+1000?'Changed after submission':'New monthly calendar'}
function updateCard(item){const photo=item.profile_photo_url||'/assets/flowtel-pinkrose.png',zone=timezoneDisplayName(item.timezone,new Date())||item.timezone||'Timezone not entered';return`<article class="availability-update-card" data-update-member="${esc(item.member_id)}" data-update-month="${esc(item.month_start)}"><header><div class="availability-update-person"><img src="${esc(photo)}" alt="" onerror="this.onerror=null;this.src='/assets/flowtel-pinkrose.png'"><div><p class="eyebrow">${esc(updateReason(item))}</p><h3>${esc(item.display_name||'Flow FM Priestess')}</h3><p>${esc(monthLabel(item.month_start))} · ${esc(zone)}</p></div></div><span>UPDATE ACUITY</span></header>${ownerMonthCalendar(item)}<footer><p>${item.days?.some(day=>day.is_override)?'Edited dates are marked so you can see where she changed the seasonal rhythm.':'This month currently follows her projected Inner Season rhythm.'}</p><button type="button" data-acknowledge-update>Mark Updated in Acuity</button></footer><p class="availability-update-message" role="status"></p></article>`}
function bindUpdateQueue(){updateList.querySelectorAll('[data-acknowledge-update]').forEach(button=>button.addEventListener('click',async()=>{const card=button.closest('[data-update-member]'),output=card.querySelector('.availability-update-message');button.disabled=true;button.textContent='SAVING…';try{await acknowledgeFlowFmAvailabilityMonth(card.dataset.updateMember,card.dataset.updateMonth);monthUpdates=await loadFlowFmAvailabilityMonthOwnerView();output.textContent='Marked updated in Acuity.';renderUpdateQueue();renderSummary();render();}catch(error){button.disabled=false;button.textContent='MARK UPDATED IN ACUITY';output.textContent=error?.message||'This update could not be cleared.';}}))}
function renderUpdateQueue(){const pending=monthUpdates.filter(item=>item.pending_owner_update===true);updateQueue.hidden=pending.length===0;updateCount.textContent=`${pending.length} ${pending.length===1?'UPDATE':'UPDATES'} WAITING`;updateList.innerHTML=pending.map(updateCard).join('');bindUpdateQueue()}
async function init(){try{[rows,monthUpdates]=await Promise.all([loadFlowFmAvailabilityOwnerView(),loadFlowFmAvailabilityMonthOwnerView()]);message.textContent='';toolbar.hidden=false;renderSummary();renderUpdateQueue();render()}catch(e){message.textContent='';gate.hidden=false;gate.innerHTML=`<p class="eyebrow">OWNER ADMINISTRATION</p><h2>Availability could not be opened.</h2><p>${esc(e?.message||'Run migration 067, then return to this room.')}</p>`}}
search.addEventListener('input',render);
filter.addEventListener('change',render);
init();
