import { renderTopNav,escapeHtml } from '/flow-fm/ui.js?v=0.10.81';
import { getCurrentProfile } from '/shared/flowtel.js?v=0.10.81';
import { loadWombMagicScheduling,loadWombMagicDates,loadWombMagicTimes,bookWombMagicCall,rescheduleWombMagicCall,cancelWombMagicCall } from '/shared/acuity-scheduling.js?v=0.10.81';
const nav=document.getElementById('topNav'),message=document.getElementById('pageMessage'),currentCall=document.getElementById('currentCall'),experience=document.getElementById('bookingExperience'),gate=document.getElementById('bookingGate'),mentorGrid=document.getElementById('mentorGrid'),monthInput=document.getElementById('monthInput'),dateGrid=document.getElementById('dateGrid'),timeGrid=document.getElementById('timeGrid'),consentCard=document.getElementById('consentCard'),consentCopy=document.getElementById('consentCopy'),consentInput=document.getElementById('consentInput'),bookButton=document.getElementById('bookButton');
let data=null,providerId='',selectedDate='',selectedSlot=null,rescheduling=null;
nav.innerHTML=renderTopNav('womb-magic');
const pad=n=>String(n).padStart(2,'0');
const now=new Date();monthInput.value=`${now.getFullYear()}-${pad(now.getMonth()+1)}`;
function setMessage(text){message.textContent=text||'';}
function formatDate(value,withTime=true){const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value||'');return new Intl.DateTimeFormat('en-US',withTime?{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:data?.member_timezone}:{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(d)}
function dateValue(item){return String(item?.date||item?.day||item||'').slice(0,10)}
function slotValue(item){return String(item?.time||item?.datetime||item?.value||item||'')}
function providerForSlot(item){if(item?.provider_id)return data.providers.find(p=>p.provider_id===item.provider_id)||null;const calendar=String(item?.calendarID||item?.calendar_id||'');return data.providers.find(p=>String(p.calendar_id)===calendar)||data.providers.find(p=>p.provider_id===providerId)||null}
function renderMentors(){mentorGrid.innerHTML=data.providers.map(p=>`<button class="mentor-card ${providerId===p.provider_id?'active':''}" data-provider-id="${escapeHtml(p.provider_id)}" type="button">${p.photo_url?`<img src="${escapeHtml(p.photo_url)}" alt="">`:''}<h3>${escapeHtml(p.display_name)}</h3><small>${escapeHtml([p.location,p.timezone].filter(Boolean).join(' · '))}</small><p>${escapeHtml((p.bio||p.modalities||'Available to hold your Womb Magic call.').slice(0,210))}</p></button>`).join('');mentorGrid.querySelectorAll('[data-provider-id]').forEach(b=>b.onclick=()=>{providerId=b.dataset.providerId;mentorGrid.hidden=false;document.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));renderMentors();dateGrid.innerHTML='';timeGrid.innerHTML='';consentCard.hidden=true;});}
function renderCurrent(){const call=data.consuming_appointment||data.appointments.find(a=>['scheduled','rescheduled'].includes(a.status)&&new Date(a.starts_at)>new Date());if(!call){currentCall.hidden=true;return;}currentCall.hidden=false;currentCall.innerHTML=`<header><div><p class="eyebrow">YOUR UPCOMING CALL</p><h2>Womb Magic with ${escapeHtml(call.practitioner_name||'a Flow FM Priestess')}</h2></div><span class="call-status">${escapeHtml(call.status.toUpperCase())}</span></header><div class="call-meta"><div><small>Date + time</small><strong>${escapeHtml(formatDate(call.starts_at))}</strong></div><div><small>Duration</small><strong>45 minutes</strong></div><div><small>Your timezone</small><strong>${escapeHtml(call.client_timezone||data.member_timezone)}</strong></div></div><div class="call-actions"><button type="button" id="rescheduleCall">Reschedule</button><button type="button" id="cancelCall">Cancel Call</button></div>`;document.getElementById('rescheduleCall').onclick=()=>{rescheduling=call;experience.hidden=false;setMessage('Choose a new date and time for this call.');experience.scrollIntoView({behavior:'smooth'});};document.getElementById('cancelCall').onclick=async()=>{if(!confirm('Cancel this Womb Magic call? Your monthly booking will become available again.'))return;try{setMessage('Cancelling your call…');await cancelWombMagicCall(call.id);await init();}catch(e){setMessage(e.message)}};}
async function loadDates(){try{setMessage('Opening available dates…');dateGrid.innerHTML='';timeGrid.innerHTML='';consentCard.hidden=true;const result=await loadWombMagicDates({month:monthInput.value,provider_id:providerId,timezone:data.member_timezone});const dates=(result.dates||[]).map(dateValue).filter(Boolean);dateGrid.innerHTML=dates.length?dates.map(d=>`<button type="button" class="date-button" data-date="${d}">${escapeHtml(formatDate(`${d}T12:00:00Z`,false))}</button>`).join(''):'<p>No dates are currently open in this month.</p>';dateGrid.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>loadTimes(b.dataset.date,b));setMessage('');}catch(e){setMessage(e.message)}}
async function loadTimes(date,button){try{selectedDate=date;dateGrid.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));setMessage('Finding available times…');const result=await loadWombMagicTimes({date,provider_id:providerId,timezone:data.member_timezone,ignore_appointment_id:rescheduling?.acuity_appointment_id});const slots=result.times||[];timeGrid.innerHTML=slots.length?slots.map((slot,i)=>`<button type="button" class="time-button" data-slot="${i}">${escapeHtml(formatDate(slotValue(slot)))}</button>`).join(''):'<p>No times remain on this date.</p>';timeGrid.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>selectSlot(slots[Number(b.dataset.slot)],b));setMessage('');}catch(e){setMessage(e.message)}}
function selectSlot(slot,button){selectedSlot=slot;timeGrid.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));const provider=providerForSlot(slot);if(provider)providerId=provider.provider_id;consentCopy.textContent=data.service.consent_language;consentCard.hidden=false;consentInput.checked=false;bookButton.disabled=true;bookButton.textContent=rescheduling?'Confirm New Time':'Consent + Book My Call';}
consentInput.onchange=()=>bookButton.disabled=!consentInput.checked;
bookButton.onclick=async()=>{const provider=providerForSlot(selectedSlot);if(!provider){setMessage('Choose a Priestess for this appointment time.');return;}try{bookButton.disabled=true;setMessage(rescheduling?'Rescheduling your call…':'Preparing your Womb Magic call…');if(rescheduling)await rescheduleWombMagicCall({appointment_id:rescheduling.id,datetime:slotValue(selectedSlot),timezone:data.member_timezone});else await bookWombMagicCall({provider_id:provider.provider_id,datetime:slotValue(selectedSlot),timezone:data.member_timezone,consent:true,phone:document.getElementById('phoneInput')?.value||''});rescheduling=null;await init();}catch(e){setMessage(e.message);bookButton.disabled=false;}};
document.getElementById('loadDatesButton').onclick=loadDates;document.querySelector('[data-provider=""]').onclick=()=>{providerId='';mentorGrid.hidden=true;document.querySelectorAll('.choice').forEach(x=>x.classList.toggle('active',x.dataset.provider===''));dateGrid.innerHTML='';timeGrid.innerHTML='';};document.getElementById('choosePriestessButton').onclick=()=>{mentorGrid.hidden=false;document.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));document.getElementById('choosePriestessButton').classList.add('active');renderMentors();};
async function init(){try{setMessage('Preparing Womb Magic…');const profile=await getCurrentProfile();if(!profile){gate.hidden=false;gate.innerHTML='<h2>Use your Room Key</h2><p>Sign in through Flowtel before booking a call.</p><a href="/client/">Enter the Flowtel</a>';experience.hidden=true;return;}data=await loadWombMagicScheduling();renderMentors();renderCurrent();experience.hidden=!data.eligible&&!(data.consuming_appointment&&['cancelled','failed'].includes(data.consuming_appointment.status));if(!data.providers.length){experience.hidden=true;gate.hidden=false;gate.innerHTML='<h2>Womb Magic is being prepared</h2><p>No Mentor calendars are mapped yet. Please return soon.</p>';}else gate.hidden=true;setMessage(data.eligible?'':'Your complimentary call for this month is already scheduled.');}catch(e){setMessage(e.message);experience.hidden=true;gate.hidden=false;gate.innerHTML='<h2>The scheduling room is not open yet</h2><p>'+escapeHtml(e.message)+'</p>';}}
init();
