// Caddie Magic v0.5.0 — owner-approved Caddie Desk with requests, availability, and consultations only.

import { requireCaddieMagicAccess } from "../../shared/caddie-magic-access.js?v=0.5.0";
import {
  getMyCaddieProfile,
  saveMyCaddieProfile,
  setAcceptingPlayerRequests,
  listMyPlayerRequests,
  respondToPlayerRequest,
  listMyAvailabilitySlots,
  addMyAvailabilitySlot,
  removeMyAvailabilitySlot,
  listMyConsultations,
  cancelConsultation,
  completeConsultation,
  getPlayerConsultationSnapshot,
} from "../../shared/caddie-magic-network.js?v=0.5.0";

const $ = (id)=>document.getElementById(id);
let profile=null, requests=[], slots=[], consultations=[];
function escapeHtml(value=""){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function setMessage(node,text="",error=false){if(node){node.textContent=text;node.classList.toggle("error",error);}}
function formatDate(value){if(!value)return "—";const d=new Date(`${String(value).slice(0,10)}T12:00:00`);return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(d);}
function formatDateTime(value){if(!value)return "—";return new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(value));}
function statusLabel(value=""){return String(value).replaceAll("_"," ").replace(/\b\w/g,(m)=>m.toUpperCase());}
function active(){return profile?.status==="active";}

function hydrateProfile(){
  $("caddieDisplayName").value=profile?.display_name||"";$("caddieProfessionalTitle").value=profile?.professional_title||"";$("caddieYearsExperience").value=profile?.years_experience??"";$("caddieCity").value=profile?.city||"";$("caddieTimezone").value=profile?.timezone||"America/Los_Angeles";$("caddieProfilePhotoUrl").value=profile?.profile_photo_url||"";$("caddieCoursesServed").value=profile?.courses_served||"";$("caddiePebbleExperience").value=profile?.pebble_beach_experience||"";$("caddiePhilosophy").value=profile?.philosophy||"";$("caddieConsultationMethod").value=profile?.consultation_method||"";$("caddieConsultationDuration").value=String(profile?.consultation_duration_minutes||30);$("caddieMeetingLink").value=profile?.meeting_link||"";
  $("caddieProfileStatus").textContent=statusLabel(profile?.status||"invited");
  const locked=["submitted"].includes(profile?.status);$("submitCaddieProfileButton").disabled=locked||active();$("submitCaddieProfileButton").textContent=locked?"Awaiting Approval":active()?"Profile Active":"Submit for Approval";
  $("activeDeskControls").classList.toggle("hidden",!active());$("playerRequestsCard").classList.toggle("hidden",!active());$("availabilityDeskCard").classList.toggle("hidden",!active());$("consultationsDeskCard").classList.toggle("hidden",!active());
  $("acceptingRequestsToggle").checked=Boolean(profile?.accepting_requests);renderAcceptingLabel();
}
function profilePayload(){return{displayName:$("caddieDisplayName").value,professionalTitle:$("caddieProfessionalTitle").value,yearsExperience:$("caddieYearsExperience").value,city:$("caddieCity").value,timezone:$("caddieTimezone").value,profilePhotoUrl:$("caddieProfilePhotoUrl").value,coursesServed:$("caddieCoursesServed").value,pebbleBeachExperience:$("caddiePebbleExperience").value,philosophy:$("caddiePhilosophy").value,consultationMethod:$("caddieConsultationMethod").value,consultationDurationMinutes:$("caddieConsultationDuration").value,meetingLink:$("caddieMeetingLink").value};}
async function saveProfile(submit=false){const button=submit?$("submitCaddieProfileButton"):$("saveCaddieDraftButton");button.disabled=true;setMessage($("profileMessage"),submit?"Submitting your Caddie Profile...":"Saving your Caddie Profile...");try{profile=await saveMyCaddieProfile(profilePayload(),{submit});setMessage($("profileMessage"),submit?"Profile submitted for owner approval.":"Caddie Profile saved.");}catch(error){setMessage($("profileMessage"),error?.message||"The Caddie Profile could not be saved.",true);}finally{button.disabled=false;if(profile)hydrateProfile();}}
function renderAcceptingLabel(){$("acceptingRequestsLabel").textContent=$("acceptingRequestsToggle").checked?"Accepting player requests":"Not accepting requests";}

function consentMarkup(row){return[row.share_scorecard&&"Scorecard",row.share_score_map&&"Score Map",row.share_compass&&"Compass",row.share_upcoming_golf&&"Calendar"].filter(Boolean).map((v)=>`<span>${escapeHtml(v)}</span>`).join("")||"<span>Profile only</span>";}
function renderRequests(){const waiting=requests.filter((r)=>r.status==="requested").length;$("requestCount").textContent=`${waiting} waiting`;$("requestList").innerHTML=requests.length?requests.map((r)=>`<article class="desk-request-row"><div><h3>${escapeHtml(r.player_name||"Player")}</h3><p>${r.anticipated_trip_date?`Pebble Beach date ${escapeHtml(formatDate(r.anticipated_trip_date))} · `:""}${escapeHtml(r.consultation_goal||"Consultation request")}</p>${r.course_itinerary?`<p>${escapeHtml(r.course_itinerary)}</p>`:""}<div class="request-consent">${consentMarkup(r)}</div></div><div class="desk-row-actions">${r.status==="requested"?`<button class="cm-button" data-respond-request="${escapeHtml(r.request_id)}" data-response="accepted">Accept</button><button class="cm-button secondary" data-respond-request="${escapeHtml(r.request_id)}" data-response="declined">Decline</button>`:r.status==="accepted"?`<button class="cm-button" data-open-snapshot="${escapeHtml(r.request_id)}">Open Read-Only Preparation</button>`:`<span class="desk-status">${escapeHtml(statusLabel(r.status))}</span>`}</div></article>`).join(""):`<div class="desk-empty">No player requests have arrived yet.</div>`;
  document.querySelectorAll("[data-respond-request]").forEach((b)=>b.addEventListener("click",async()=>{b.disabled=true;try{await respondToPlayerRequest(b.dataset.respondRequest,b.dataset.response);await reloadOperationalData();}catch(error){setMessage($("deskMessage"),error?.message||"The request could not be updated.",true);b.disabled=false;}}));
  document.querySelectorAll("[data-open-snapshot]").forEach((b)=>b.addEventListener("click",()=>openSnapshot(b.dataset.openSnapshot)));
}
function renderSlots(){$("slotList").innerHTML=slots.length?slots.map((s)=>`<article class="desk-slot-row"><div><h3>${escapeHtml(formatDateTime(s.starts_at))}</h3><p>Ends ${escapeHtml(formatDateTime(s.ends_at))} · ${escapeHtml(statusLabel(s.status))}</p></div><div class="desk-row-actions">${s.status==="available"?`<button class="cm-button secondary" data-remove-slot="${escapeHtml(s.id)}">Remove</button>`:""}</div></article>`).join(""):`<div class="desk-empty">No consultation availability has been posted.</div>`;document.querySelectorAll("[data-remove-slot]").forEach((b)=>b.addEventListener("click",async()=>{if(!window.confirm("Remove this open time?"))return;b.disabled=true;try{await removeMyAvailabilitySlot(b.dataset.removeSlot);await reloadOperationalData();}catch(error){setMessage($("availabilityStatus"),error?.message||"The availability could not be removed.",true);b.disabled=false;}}));}
function renderConsultations(){
  const caddieConsultations=consultations.filter((c)=>c.viewer_role==="caddie");
  $("deskConsultationList").innerHTML=caddieConsultations.length?caddieConsultations.map((c)=>{
    const mayComplete=c.status==="scheduled"&&new Date(c.starts_at).getTime()<=Date.now();
    return `<article class="desk-consultation-row"><div><h3>${escapeHtml(c.player_name||"Player Consultation")}</h3><p>${escapeHtml(formatDateTime(c.starts_at))} · ${escapeHtml(c.consultation_method||"Consultation")}</p><p>Status: ${escapeHtml(statusLabel(c.status))}</p></div><div class="desk-row-actions">${c.status==="scheduled"&&c.meeting_link?`<a class="cm-button" href="${escapeHtml(c.meeting_link)}" target="_blank" rel="noopener">Open Meeting</a>`:""}${mayComplete?`<button class="cm-button" data-complete-consultation="${escapeHtml(c.consultation_id)}">Mark Complete</button>`:""}${c.status==="scheduled"?`<button class="cm-button secondary" data-cancel-consultation="${escapeHtml(c.consultation_id)}">Cancel</button>`:""}</div></article>`;
  }).join(""):`<div class="desk-empty">No consultations are scheduled.</div>`;
  document.querySelectorAll("[data-complete-consultation]").forEach((b)=>b.addEventListener("click",async()=>{if(!window.confirm("Mark this consultation complete?"))return;b.disabled=true;try{await completeConsultation(b.dataset.completeConsultation);await reloadOperationalData();}catch(error){setMessage($("deskMessage"),error?.message||"The consultation could not be completed.",true);b.disabled=false;}}));
  document.querySelectorAll("[data-cancel-consultation]").forEach((b)=>b.addEventListener("click",async()=>{if(!window.confirm("Cancel this consultation?"))return;b.disabled=true;try{await cancelConsultation(b.dataset.cancelConsultation);await reloadOperationalData();}catch(error){setMessage($("deskMessage"),error?.message||"The consultation could not be cancelled.",true);b.disabled=false;}}));
}

function snapshotEntries(entries=[]){return entries.length?`<div class="snapshot-entry-list">${entries.slice(0,20).map((e)=>`<article class="snapshot-entry"><time>${escapeHtml(formatDate(e.round_date))}${e.moon_day?` · Day ${escapeHtml(e.moon_day)}`:""}</time><p>${escapeHtml(e.swing_thoughts||e.course_played||"Score logged")}</p>${e.score!=null?`<strong>${escapeHtml(e.score)}</strong>`:""}</article>`).join("")}</div>`:`<div class="desk-empty">No shared entries are available.</div>`;}
async function openSnapshot(requestId){$("snapshotContent").innerHTML=`<div class="snapshot-wrap"><p class="cm-eyebrow">CONSULTATION PREPARATION</p><h2>Opening read-only player data...</h2></div>`;$("snapshotDialog").showModal();try{const s=await getPlayerConsultationSnapshot(requestId);const player=s?.player||{},request=s?.request||{},compass=s?.compass||null,upcoming=Array.isArray(s?.upcoming_golf)?s.upcoming_golf:[];$("snapshotContent").innerHTML=`<div class="snapshot-wrap"><p class="cm-eyebrow">READ-ONLY CONSULTATION PREPARATION</p><h2>${escapeHtml(player.name||"Player")}</h2><p class="cm-muted">You can study what the player consented to share. You cannot edit records, send notes, create assignments, or message the player inside Caddie Magic.</p><section class="snapshot-section"><div class="snapshot-grid"><article class="snapshot-data-card"><span>Trip Date</span><strong>${escapeHtml(formatDate(request.anticipated_trip_date))}</strong></article><article class="snapshot-data-card"><span>Score Range</span><strong>${escapeHtml(player.handicap_or_score_range||"Not provided")}</strong></article><article class="snapshot-data-card"><span>Home Course</span><strong>${escapeHtml(player.home_course||"Not provided")}</strong></article><article class="snapshot-data-card"><span>Consultation Goal</span><p>${escapeHtml(request.consultation_goal||"Not provided")}</p></article></div></section>${compass?`<section class="snapshot-section"><p class="cm-eyebrow">CADDIE COMPASS</p><div class="snapshot-grid"><article class="snapshot-data-card"><span>North Club</span><strong>${escapeHtml(compass.north_club)}</strong></article><article class="snapshot-data-card"><span>East Club</span><strong>${escapeHtml(compass.east_club)}</strong></article><article class="snapshot-data-card"><span>West Club</span><strong>${escapeHtml(compass.west_club)}</strong></article><article class="snapshot-data-card"><span>South Club</span><strong>${escapeHtml(compass.south_club)}</strong></article></div></section>`:""}${Array.isArray(s?.scorecard)&&s.scorecard.length?`<section class="snapshot-section"><p class="cm-eyebrow">SCORECARD</p>${snapshotEntries(s.scorecard)}</section>`:""}${Array.isArray(s?.score_map)&&s.score_map.length?`<section class="snapshot-section"><p class="cm-eyebrow">SCORE MAP</p>${snapshotEntries(s.score_map)}</section>`:""}${upcoming.length?`<section class="snapshot-section"><p class="cm-eyebrow">UPCOMING GOLF</p>${upcoming.map((e)=>`<article class="snapshot-entry"><time>${escapeHtml(formatDate(e.date_start))}</time><p>${escapeHtml(e.title||e.course||"Upcoming Golf")}</p><strong>${escapeHtml(e.event_type||"")}</strong></article>`).join("")}</section>`:""}</div>`;}catch(error){$("snapshotContent").innerHTML=`<div class="snapshot-wrap"><p class="cm-message error">${escapeHtml(error?.message||"The preparation view could not be opened.")}</p></div>`;}}

async function reloadOperationalData(){if(!active())return;[requests,slots,consultations]=await Promise.all([listMyPlayerRequests(),listMyAvailabilitySlots(),listMyConsultations()]);renderRequests();renderSlots();renderConsultations();}
async function boot(){try{await requireCaddieMagicAccess();profile=await getMyCaddieProfile();$("deskLoadingCard").classList.add("hidden");if(!profile){$("notInvitedCard").classList.remove("hidden");return;}$("deskPage").classList.remove("hidden");hydrateProfile();await reloadOperationalData();}catch(error){setMessage($("deskMessage"),error?.message||"The Caddie Desk could not be opened.",true);}}

$("saveCaddieDraftButton")?.addEventListener("click",()=>saveProfile(false));$("submitCaddieProfileButton")?.addEventListener("click",()=>saveProfile(true));$("acceptingRequestsToggle")?.addEventListener("change",async()=>{renderAcceptingLabel();try{profile=await setAcceptingPlayerRequests($("acceptingRequestsToggle").checked);}catch(error){$("acceptingRequestsToggle").checked=!$("acceptingRequestsToggle").checked;renderAcceptingLabel();setMessage($("deskMessage"),error?.message||"The request setting could not be changed.",true);}});
$("availabilityForm")?.addEventListener("submit",async(event)=>{event.preventDefault();const button=event.currentTarget.querySelector("button");button.disabled=true;setMessage($("availabilityStatus"),"Adding availability...");try{const start=$("availabilityStart").value,end=$("availabilityEnd").value;await addMyAvailabilitySlot(new Date(start).toISOString(),new Date(end).toISOString());event.currentTarget.reset();setMessage($("availabilityStatus"),"Availability added.");await reloadOperationalData();}catch(error){setMessage($("availabilityStatus"),error?.message||"The availability could not be added.",true);}finally{button.disabled=false;}});
$("snapshotDialogClose")?.addEventListener("click",()=>$("snapshotDialog").close());$("snapshotDialog")?.addEventListener("click",(event)=>{if(event.target===$("snapshotDialog"))$("snapshotDialog").close();});
boot();
