// Caddie Magic v0.5.0 — personalized Cardinal Club Rooms.

import { supabase } from "../../../shared/supabase.js";
import { requireCaddieMagicAccess } from "../../../shared/caddie-magic-access.js?v=0.5.0";
import { getMyCaddieMagicProfile, getMyActiveCompass } from "../../../shared/caddie-magic-compass.js?v=0.5.0";

const $=(id)=>document.getElementById(id);
const directions={
  north:{label:"North Club",symbol:"N",phase:"Half New Moon Phase",phaseLabel:"Last Quarter Phase",days:"Moon Days 20–26",field:"north_club"},
  east:{label:"East Club",symbol:"E",phase:"Full Moon Phase",phaseLabel:"Full Moon Phase",days:"Moon Days 12–19",field:"east_club"},
  south:{label:"South Club",symbol:"S",phase:"Half Full Moon Phase",phaseLabel:"First Quarter Phase",days:"Moon Days 6–11",field:"south_club"},
  west:{label:"West Club",symbol:"W",phase:"New Moon Phase",phaseLabel:"New Moon Phase",days:"Moon Days 27–5",field:"west_club"},
};
const key=String(new URLSearchParams(location.search).get("direction")||"north").toLowerCase();
const room=directions[key]||directions.north;
let profile=null,compass=null,mine=[],everyone=[],scope="mine",view="thoughts_scores";
function escapeHtml(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function setMessage(node,text="",error=false){if(node){node.textContent=text;node.classList.toggle("error",error);}}
function formatDate(value){if(!value)return "";const d=new Date(`${String(value).slice(0,10)}T12:00:00`);return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(d);}
function normalizePhase(value=""){const v=String(value).toLowerCase();if(v.includes("half new")||v.includes("last quarter")||v.includes("third"))return "Half New Moon Phase";if(v.includes("half full")||v.includes("first quarter"))return "Half Full Moon Phase";if(v.includes("full")&&!v.includes("half"))return "Full Moon Phase";if(v.includes("new")&&!v.includes("half"))return "New Moon Phase";return value;}
function scores(entries){return entries.map((e)=>Number(e.score)).filter(Number.isFinite);}
function average(entries){const values=scores(entries);return values.length?Math.round((values.reduce((a,b)=>a+b,0)/values.length)*10)/10:"—";}
function best(entries){const values=scores(entries);return values.length?Math.min(...values):"—";}
function renderHeader(){const club=compass?.[room.field]||"Your Club";document.title=`${room.label} · Caddie Magic`;$("clubDirectionEyebrow").textContent=room.label.toUpperCase();$("clubRoomTitle").textContent=room.label.toUpperCase();$("clubRoomLead").textContent=`${club} · ${room.phaseLabel}`;$("clubPhaseLabel").textContent=`${room.phaseLabel.toUpperCase()} · ${room.days.toUpperCase()}`;$("personalizedClubName").textContent=club;$("clubPhaseCopy").textContent=`Every score and swing thought captured during ${room.phaseLabel} gathers here through your ${club}.`;$("clubRoomSymbol").textContent=room.symbol;document.querySelectorAll(".club-room-nav a").forEach((a)=>{const dir=new URL(a.href).searchParams.get("direction");if(dir===key)a.setAttribute("aria-current","page");});}
function renderStats(){const entries=mine;$("clubStats").innerHTML=`<article class="club-stat"><span>Personal Entries</span><strong>${entries.length}</strong></article><article class="club-stat"><span>Average Score</span><strong>${escapeHtml(average(entries))}</strong></article><article class="club-stat"><span>Best Score</span><strong>${escapeHtml(best(entries))}</strong></article>`;}
function entryMarkup(entry,anonymous=false){const hasScore=entry.score!==null&&entry.score!==""&&Number.isFinite(Number(entry.score));if(view==="scores")return hasScore?`<article class="club-entry is-score-only"><strong>${escapeHtml(entry.score)}</strong></article>`:"";const thought=String(entry.swing_thoughts??entry.swing_thought??"").trim();return `<article class="club-entry"><div><div class="club-entry-meta"><span>Moon Day ${escapeHtml(entry.moon_day||"—")}</span>${!anonymous&&entry.round_date?`<span>${escapeHtml(formatDate(entry.round_date))}</span>`:""}</div><p>${thought?escapeHtml(thought):"Score logged without a swing thought."}</p>${!anonymous&&entry.course_played?`<em>${escapeHtml(entry.course_played)}</em>`:""}</div>${hasScore?`<strong>${escapeHtml(entry.score)}</strong>`:""}</article>`;}
function renderFeed(){const source=scope==="mine"?mine:everyone;const filtered=view==="scores"?source.filter((e)=>e.score!==null&&e.score!==""):source;$("clubRoomFeed").innerHTML=filtered.length?filtered.map((e)=>entryMarkup(e,scope==="everyone")).join(""):`<div class="club-empty">No ${view==="scores"?"scores":"entries"} have landed in this ${room.label} view yet.</div>`;$("anonymousNote").textContent=scope==="mine"?"Your entries include dates and course context. Use Everyone’s to witness anonymous scores and swing thoughts from players who share with the Locker Room.":"Everyone’s entries are anonymous. Player names, courses, and exact dates are never shown here.";document.querySelectorAll("[data-scope]").forEach((b)=>b.classList.toggle("is-active",b.dataset.scope===scope));document.querySelectorAll("[data-view]").forEach((b)=>b.classList.toggle("is-active",b.dataset.view===view));}
async function loadData(){profile=await getMyCaddieMagicProfile();compass=await getMyActiveCompass();if(!profile)throw new Error("Create your Player Profile before opening a Cardinal Club.");if(!compass)throw new Error("Save your Caddie Compass before opening its Cardinal Clubs.");const [mineResult,everyoneResult]=await Promise.all([supabase.from("caddie_magic_round_logs").select("*").eq("player_profile_id",profile.id).order("round_date",{ascending:false}).order("created_at",{ascending:false}),supabase.rpc("caddie_magic_get_locker_room_entries",{p_moon_cycle_start:null,p_moon_phase:room.phase})]);if(mineResult.error)throw mineResult.error;if(everyoneResult.error)throw everyoneResult.error;mine=(mineResult.data||[]).filter((e)=>normalizePhase(e.moon_phase)===room.phase);everyone=everyoneResult.data||[];}
async function boot(){try{await requireCaddieMagicAccess();await loadData();renderHeader();renderStats();renderFeed();$("clubLoadingCard").classList.add("hidden");$("clubRoomPage").classList.remove("hidden");}catch(error){setMessage($("clubMessage"),error?.message||"This Cardinal Club could not be opened.",true);}}
$("scopeToggle")?.addEventListener("click",(event)=>{const b=event.target.closest("[data-scope]");if(!b)return;scope=b.dataset.scope;renderFeed();});$("viewToggle")?.addEventListener("click",(event)=>{const b=event.target.closest("[data-view]");if(!b)return;view=b.dataset.view;renderFeed();});boot();
