// shared/womb-work.js
// Flow FM inner curriculum modules sourced from the onboarding guide.

export const WOMB_WORK_MODULES = [
  { index: 1, arc: 'Big Vision', months: 'Months 1–3', title: 'Collect cycle data', description: 'Begin observing the body, the bleed, the moon, and the patterns that will become your source material.' , practice: 'Track one full cycle or moon cycle without trying to fix anything.', prompt: 'What patterns begin to appear when I simply observe?', squarespaceUrl: '' },
  { index: 2, arc: 'Big Vision', months: 'Months 1–3', title: 'Study your inner seasons', description: 'Learn the four inner seasons and how your body, energy, and emotions move through them.' , practice: 'Map your energy, mood, and needs across the four inner seasons.', prompt: 'Which inner season feels easiest for me to honor, and which one do I override?', squarespaceUrl: '' },
  { index: 3, arc: 'Big Vision', months: 'Months 1–3', title: 'Cultivate your BIG VISION', description: 'Name the larger life and business vision that wants to be carried by your womb wisdom.' , practice: 'Write the BIG VISION as if your body already knows the way.', prompt: 'What vision keeps returning even when I try to be practical?', squarespaceUrl: '' },
  { index: 4, arc: 'Practice', months: 'Months 4–6', title: 'Plan with your cycle', description: 'Use your cycle and the moon as a planning rhythm so your work supports your nervous system.' , practice: 'Choose one week of work and place each task in the moon phase where it belongs.', prompt: 'What becomes easier when I stop forcing every task into every day?', squarespaceUrl: '' },
  { index: 5, arc: 'Practice', months: 'Months 4–6', title: 'Set energetic boundaries', description: 'Create cleaner containers, clearer choices, and stronger boundaries around your life force.' , practice: 'Name three energetic boundaries that would protect your practice.', prompt: 'Where does my body already know the answer is no?', squarespaceUrl: '' },
  { index: 6, arc: 'Practice', months: 'Months 4–6', title: 'Meet your Angelic Army', description: 'Build a relationship with unseen support and the spiritual architecture around your work.' , practice: 'Create a simple altar or note for the unseen support around your work.', prompt: 'What support am I allowed to receive without earning it first?', squarespaceUrl: '' },
  { index: 7, arc: 'Get Visible', months: 'Months 7–9', title: 'Expand your presence to be seen', description: 'Stretch your visibility with softness, steadiness, and greater truth in your expression.' , practice: 'Publish or share one honest expression that lets more of you be seen.', prompt: 'What part of my presence is asking to stop hiding?', squarespaceUrl: '' },
  { index: 8, arc: 'Get Visible', months: 'Months 7–9', title: 'Embody your priestess identity', description: 'Move from learning the work to becoming the woman who naturally holds it.' , practice: 'Write the identity statement of the priestess/practitioner you are becoming.', prompt: 'Who am I when I stop waiting for permission?', squarespaceUrl: '' },
  { index: 9, arc: 'Get Visible', months: 'Months 7–9', title: 'Magnetize your resources', description: 'Tend the energetics, practical pathways, and receptivity required for support and overflow.' , practice: 'List the resources your Queendom requires and one grounded path for each.', prompt: 'What form of support am I ready to magnetize now?', squarespaceUrl: '' },
  { index: 10, arc: 'Launch', months: 'Months 10–12', title: 'Unlock your creative genius', description: 'Open the inner current that wants to create, teach, and lead in your own way.' , practice: 'Create one small teaching, ritual, or transmission from your own lived wisdom.', prompt: 'What does my creative genius already know how to make?', squarespaceUrl: '' },
  { index: 11, arc: 'Launch', months: 'Months 10–12', title: 'Create your offerings', description: 'Shape your medicine into living offers that can be received, held, and exchanged.' , practice: 'Shape one offer with a name, promise, container, and next step.', prompt: 'What can someone actually receive from me now?', squarespaceUrl: '' },
  { index: 12, arc: 'Launch', months: 'Months 10–12', title: 'Launch your BIG VISION', description: 'Bring the vision out of the subtle realms and into real expression, invitation, and service.' , practice: 'Choose a launch doorway and write the invitation in your real voice.', prompt: 'What invitation would feel clean, true, and alive?', squarespaceUrl: '' },
  { index: 13, arc: 'Celebrate', months: 'Month 13', title: 'Open the Golden Gates to your Queendom', description: 'Integrate what you have become and step into the next spiral of leadership.' , practice: 'Reflect on the spiral and name what opens as your Queendom door.', prompt: 'Who have I become after watching myself for 13 moons?', squarespaceUrl: '' },
];

export function getWombWorkModule(index) {
  return WOMB_WORK_MODULES.find(item => Number(item.index) === Number(index)) || null;
}
